### ISSUE TITLE
[Terminator] The prompt has no color

### ISSUE THREAD

**Issue by ghost** [win0err/aphrodite-terminal-theme#5]
Hi,

I had an issue when I changed my terminal. Before, I was working with gnome-terminal and I was able to enjoy this super theme. Everything worked properly. Recently, I change it to Terminator.
To my surprise, my prompt has no color. It's very annoying, because I like the color of the git branch to work.
When I change theme like agnoster for example, the color comes back.

My OS : Ubuntu 16.04LTS.
I have the last version of Oh-my-zsh

Tank you in advance

**Comment by win0err** [comment]
Hello!

It's very strange. I installed Terminator, the theme works well:
![Terminator and Gnome Terminal](https://user-images.githubusercontent.com/11278181/51043465-cd66f100-15cf-11e9-9845-f3be2989e81c.png)

Please, check Terminator preferences, maybe wrong command runs at start instead of zsh: 
![Terminator preferences](https://user-images.githubusercontent.com/11278181/51043644-40706780-15d0-11e9-8b00-c95b0247439b.png)

**Comment by ghost** [comment]
Hello

Tank you for you response !

I check the preferences, and i don't have any custom command at start...

![capture_terminator_zsh](https://user-images.githubusercontent.com/18407840/51044334-2bd8a300-15c1-11e9-8fd0-f935fe20061d.PNG)

![capture_terminator_zsh_pref](https://user-images.githubusercontent.com/18407840/51044344-3004c080-15c1-11e9-9ace-fb379d15354f.PNG)


And with gnome-terminal : 

![capture_gnome_terminal_zsh](https://user-images.githubusercontent.com/18407840/51044434-5dea0500-15c1-11e9-83cb-3a982bd13136.PNG)

**Comment by win0err** [comment]
What's the output of this command `echo $TERM $COLORTERM`?

P.S. I suggest you to take a look at [Tilix](https://gnunn1.github.io/tilix-web/). In my opinion, it is the best good looking terminal emulator on linux.

**Comment by ghost** [comment]
```shell
$ echo $TERM $COLORTERM 
xterm gnome-terminal
```

I'm going to try with Tilix

**Comment by win0err** [comment]
Maybe this will help you:
```bash
export TERM="xterm-256color"
```

If yes, simply add this line to `~/.zshrc`

**Comment by ghost** [comment]
Oh yes tank you ! This fixes my issue
