### ISSUE TITLE
seems that link is broken

### ISSUE THREAD

**Issue by vaneuk** [win0err/aphrodite-terminal-theme#6]
Hi,
https://git.io/v5ohc is not working anymore

**Comment by win0err** [comment]
Hi, @vaneuk!

1. It works fine now. 
It should redirect to https://raw.githubusercontent.com/win0err/aphrodite-terminal-theme/master/aphrodite.zsh-theme
I think it was just a temporary git.io problems.
2. I've updated README.md: 008a8d1

Please, try again.
Thank you for the issue!
