### ISSUE TITLE
Doc change

### ISSUE THREAD

**Issue by sdparkes66** [win0err/aphrodite-terminal-theme#8]
Quicker and easier way

```
cd ~
git clone https://github.com/win0err/aphrodite-terminal-theme $ZSH_CUSTOM/themes/aphrodite-terminal-theme
```

Change your ZSH_THEME to `aphrodite-terminal-theme/aphrodite`

`source .zshrc`

**Comment by win0err** [comment]
@sdparkes66, I've updated the README.md: https://github.com/win0err/aphrodite-terminal-theme#readme

Thank you.
